apiVersion: batch/v1
kind: Job
metadata:
  name: cntfrgme-job
spec:
  template:
    spec:
      containers:
      - name: cntfrgme-job
        image: yash5090/cntfrgme:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
