apiVersion: apps/v1
kind: Deployment
metadata:
  name: cntfrgme-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: cntfrgme
  template:
    metadata:
      labels:
        app: cntfrgme
    spec:
      containers:
        - name: cntfrgme
          image: yash5090/cntfrgme:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
